pdf(file = paste0("FertodControl.pdf"), width=28)
plot(get(csatorna_nevek[1])/10, main = paste(csatorna_nevek[1], "Szélsebesség [m/s]"))
plot(get(csatorna_nevek[2]), main = paste(csatorna_nevek[2], "Szélirány [°]"), ylim = c(0,360))
plot(get(csatorna_nevek[3])/10, main = paste(csatorna_nevek[3], "Csapadék [mm]"), type = "h")
plot(get(csatorna_nevek[4])/10, main = paste(csatorna_nevek[4], "Hőmérséklet [°C]"))
plot(get(csatorna_nevek[5])/10, main = paste(csatorna_nevek[5], "Páratartalom [%]"), ylim = c(0,100))
plot.zoo(C14_sens$sensor1/10, main = "C14", xaxs = "i", lwd = 2,
         ylab = "Talajhőmérséklet [°C]")
lines(as.zoo(C14_sens$sensor2/10), col = 2, lwd = 2)
lines(as.zoo(C14_sens$sensor3/10), col = 3, lwd = 2)
legend("bottomleft", legend= c(1,2,3), col = c(1,3,2), lwd = 2)
plot.zoo(C15_sens$sensor1/10, main = "C15", xaxs = "i", ylim = c(0,100), lwd = 2,
         ylab = "Talajnesvesség [%]")
lines(as.zoo(C15_sens$sensor2/10), col = 2, lwd = 2)
lines(as.zoo(C15_sens$sensor3/10), col = 3, lwd = 2)
legend("bottomleft", legend= c(1,2,3), col = c(1,3,2), lwd = 2)
plot(get(csatorna_nevek[8]), main = paste(csatorna_nevek[8], "Radiáció [W/m^2]"))
plot(get(csatorna_nevek[9]), main = paste(csatorna_nevek[9], "Akku fesz. [mV]"))
plot(get(csatorna_nevek[10]), main = paste(csatorna_nevek[10], "Napelem fesz. [mV]"))
dev.off()
