pdf(file = paste0("FertodControl.pdf"), width=28)
plot(get(csatorna_nevek[1])/10, main = paste(csatorna_nevek[1], "Szélsebesség [m/s]"))
plot(get(csatorna_nevek[2]), main = paste(csatorna_nevek[2], "Szélirány [°]"), ylim = c(0,360))
plot(get(csatorna_nevek[3])/10, main = paste(csatorna_nevek[3], "Csapadék [mm]"), type = "h")
plot(get(csatorna_nevek[4])/10, main = paste(csatorna_nevek[4], "Hőmérséklet [°C]"))
plot(get(csatorna_nevek[5])/10, main = paste(csatorna_nevek[5], "Páratartalom [%]"), ylim = c(0,100))
plot(C14_1/10, main = paste("C14_1", "Talaj hőm. [°C]"))
plot(get(csatorna_nevek[7])/10, main = paste(csatorna_nevek[7], "Talaj nedv. [%]"), ylim = c(0,100))
plot(get(csatorna_nevek[8]), main = paste(csatorna_nevek[8], "Radiáció [W/m^2]"))
plot(get(csatorna_nevek[9]), main = paste(csatorna_nevek[9], "Akku fesz. [mV]"))
plot(get(csatorna_nevek[10]), main = paste(csatorna_nevek[10], "Napelem fesz. [mV]"))
dev.off()

